[package]
name = "native-webaudio-rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.5.0"


[profile.release]
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1
